#!/bin/bash

set -e

. /opt/docker-solr/scripts/run-initdb

CORE='books'
CONFIG_SOURCE='/opt/solr/server/solr/configsets/data_driven_schema_configs'

if [[ -z $SOLR_HOME ]]; then
    coresdir="/opt/solr/server/solr/mycores"
    mkdir -p $coresdir
else
    coresdir=$SOLR_HOME
fi
coredir="$coresdir/$CORE"
if [[ ! -d $coredir ]]; then
    cp -r $CONFIG_SOURCE/ $coredir
    touch "$coredir/core.properties"
    echo created "$CORE"
else
    echo "core $CORE already exists"
fi
